name: "Deploy App to Firebase Distribution"

on:
  pull_request:
    types:
      - opened

jobs:
  run_unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run Unit Tests
        run: ./gradlew testPRODReleaseUnitTest

  upload_app_to_firebase:
    needs: run_unit_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build App
        run: ./gradlew assemblePROD

      - name: Upload and Distribute App to Firebase
        uses: mastersam07/firebase-app-distribution-action@v0.1
        with:
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          appId: ${{ secrets.FIREBASE_APP_ID }}
          file: app/PROD/release/app-PROD-release.apk
          groups: beta-testers